version: 2
jobs:
  build:
    docker:
      - image: aergus/latex
    steps:
      - checkout
      - run:
          name: Compile CV
          command: xelatex cv_10.tex
      - store_artifacts:
          path: cv_10.pdf
          destination: CV_PierreLouis_TILAK.pdf
